[package]
name = "vroom"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "^0.14.0"
sysinfo = "^0.3.6"

[[bin]]
name = "vroom"
path = "main.rs"
